### ISSUE TITLE
Add analysis jobs

### ISSUE THREAD

**Issue by aperezca** [amaltaro/scripts#3]
We are not getting info from analysis jobs because we are excluding them here: https://github.com/amaltaro/scripts/blob/master/CondorMonitoring/JobCounter.py#L569

At least for now, I'd suggest to have three groups: "production", "crab3" and "other". This is what I am doing in my queries to get 

http://submit-3.t2.ucsd.edu/CSstoragePath/aperez/HTML/jobstatus_24h.html

Other, so far, includes things like CMS connect. If/when they grow in importance we could consider subdividing it.

**Comment by amaltaro** [comment]
Antonio, I just took a look at the code and adding analysis jobs should be easy'ish. Can you just let me know what would be the job classAds that you would be interested for analysis?

Would that be exactly the same as we collect for production? Like this line
https://github.com/amaltaro/scripts/blob/master/CondorMonitoring/JobCounter.py#L600

**Comment by aperezca** [comment]
Hi Alan, I think the information should be similar, yes. One difference is of course WMAgent_SubTaskName, absent from CRAB jobs. For that we would need something equivalent, CRAB_ReqName or CRAB_Workflow.

Then, also for CMS_JobType, I think this in undefined for CRAB jobs. If for example CRAB_ReqName is set, then this is a CRAB3 job, so I would define CMS_JobType for them as "crab" or "crab3". I'd avoid analysis, as there are other schedds we may want to add to the pool and its monitoring which would also run analysis jobs but not from CRAB (such as CMS connect)

Is that reasonable?
