### ISSUE TITLE
Wrong counting of cores in condor view

### ISSUE THREAD

**Issue by aperezca** [amaltaro/scripts#5]
It seems to me that we are applying the n_cores factor twice in the condor view. We just started running multicore jobs for n_cores = 4. Look at the number of jobs and the number of cores at PIC in the last 48h:

![jobs](https://cloud.githubusercontent.com/assets/4446046/16584529/dfc37618-42bc-11e6-8c72-56a1b236a427.png)

![cores](https://cloud.githubusercontent.com/assets/4446046/16584542/f471c8c6-42bc-11e6-9617-9eea706451bb.png)

But from the historical view 

http://dashb-cms-job.cern.ch/dashboard/request.py/dailysummary#button=jobstatus&sites%5B%5D=T1_ES_PIC&sitesSort=1&start=null&end=null&timerange=last48&granularity=Hourly&generic=0&sortby=10&series=All&cores%5B%5D=All+Cores

it seems we really have ~100 jobs and 400 cores, not 400 jobs and 1600 cores
![dashboard_jobs](https://cloud.githubusercontent.com/assets/4446046/16584700/a62886cc-42bd-11e6-8395-ef770f535609.png)

![dashboard_cores](https://cloud.githubusercontent.com/assets/4446046/16584712/add4aa7c-42bd-11e6-89c8-27e84f1d325c.png)

**Comment by amaltaro** [comment]
Antonio, can you get the number of jobs running at PIC that are request 4 cores? Possible querying the global pool, just to make sure we identify the correct one first.

**Comment by amaltaro** [comment]
Do you know exactly how many jobs are running at PIC at the moment?

**Comment by amaltaro** [comment]
According to my condor queries, PIC is running 1238 single core and 268 4-cores jobs right now:

```
condor_q -global -constraint 'MATCH_EXP_JOBGLIDEIN_CMSSite == "'T1_ES_PIC'"' -af:h RequestCpus WMAgent_RequestName > out_pic
cmst1@vocms0308:/data/srv/wmagent/current $ egrep '^1' out_pic  | wc -l
1238
cmst1@vocms0308:/data/srv/wmagent/current $ egrep '^4' out_pic  | wc -l
268
```

which gives us a total of ~1238 + 4 \* 268 = 2310 cores in use at the moment.
The upper plots (condor monitoring) thus makes sense to me, while the dashboard
one seems to be wrong.

**Comment by aperezca** [comment]
Hi Alan,

I don't know what is going on… from the local monitoring we have around 2300 cores taken right now at PIC. Looking at jobs from the global pool:

aperez@submit-3 ~$ condor_q -pool cmsgwms-collector-global.cern.ch -global -constraint '(MATCH_EXP_JOBGLIDEIN_CMSSite == "'T1_ES_PIC'") && (RequestCpus == 4)' -af RequestCpus |sort |uniq -c
    251 4
aperez@submit-3 ~$ condor_q -pool cmsgwms-collector-global.cern.ch -global -constraint '(MATCH_EXP_JOBGLIDEIN_CMSSite == "'T1_ES_PIC'") && (RequestCpus == 1)' -af RequestCpus |sort |uniq -c
   1194 1

so that's 251*4 + 1194 = 2198

So let's check what the condor monitoring tells us: 
![raqiqul](https://cloud.githubusercontent.com/assets/4446046/16589365/18e0acca-42d3-11e6-87b1-9862e35fedfe.png)

![yn4uziy](https://cloud.githubusercontent.com/assets/4446046/16589379/264805ac-42d3-11e6-8715-8e2902bd8854.png)

So it's true that this looks correct as it is right now. However, what about the peak at 22h yesterday? We couldn't be running close to 4.5k cores! 

On the other hand, the dashboard view is wrong as well…

![f0luwhm](https://cloud.githubusercontent.com/assets/4446046/16589652/5ea4a652-42d4-11e6-9b20-29df97222f6b.png)

what's going on?

**Comment by aperezca** [comment]
Hi Alan,

Just checking now on multicore, 4-core, jobs running
aperez@submit-3 ~$ condor_q -pool cmsgwms-collector-global.cern.ch -global -constraint '(RequestCpus == 4) && (JobStatus == 2)' -af MATCH_EXP_JOBGLIDEIN_CMSSite RequestCpus |sort | grep -v T0|awk '{print $2}' |sort |uniq -c
   **2898 4**

and pending:
aperez@submit-3 ~$ condor_q -pool cmsgwms-collector-global.cern.ch -global -constraint '(RequestCpus == 4) && (JobStatus == 1)' -af MATCH_EXP_JOBGLIDEIN_CMSSite RequestCpus |sort | grep -v T0|awk '{print $2}' |sort |uniq -c
  **76236 4**

So, into cores, that is **11592 running, 304944 pending**.

Looking now at monitoring:

Condor view seems in fact correct for pending:
![sfo7pmn](https://cloud.githubusercontent.com/assets/4446046/16628270/5aef6d48-43b1-11e6-9952-5cdd78584545.png)
![pljtcge](https://cloud.githubusercontent.com/assets/4446046/16628271/5cb434c4-43b1-11e6-922e-ecb4bbd0662c.png)

but not for running:
![bpruzxi](https://cloud.githubusercontent.com/assets/4446046/16628324/923e68b2-43b1-11e6-8a5b-d88479510ea5.png)
![i7kn1kp](https://cloud.githubusercontent.com/assets/4446046/16628322/91ecdb28-43b1-11e6-929b-1b601b85e97f.png)

it shows about 8200 jobs, 32700 cores

the historical view
![vitixbb](https://cloud.githubusercontent.com/assets/4446046/16628758/53a276c8-43b3-11e6-9f27-e42827109c69.png)
![hkh8tot](https://cloud.githubusercontent.com/assets/4446046/16628757/5323c0c6-43b3-11e6-8fa9-007d3247a369.png)
 it shows 1000 jobs, 4000 cores running

and pending makes no sense at all…

Do you understand this? Could it be a matter of binning or re-weighting of jobs in the dashboard? I'm really lost.

**Comment by aperezca** [comment]
Looking at PIC in particular:

-From inside we are using close to 1580 cores

-From the global pool: 772_1 + 197_4 = 1560, perfect match

-Condor view:
![1roh2zd](https://cloud.githubusercontent.com/assets/4446046/16629239/5a890630-43b5-11e6-92b8-017e5f1db796.png)
![clxtbef](https://cloud.githubusercontent.com/assets/4446046/16629238/5a813a54-43b5-11e6-9c47-703be4a7939e.png)

jobs: 1288 jobs, ~400 mcore -> 400 mcore + 900 single core? Is it double counting the number of jobs?
cores: 2400 cores in total (wrong) but about 1500 are from mcore ->900 for score, which seems coherent 

-Historical view:
![1gvxvpk](https://cloud.githubusercontent.com/assets/4446046/16629462/096fe7ae-43b6-11e6-9890-fe5d2bce5ca3.png)
![jwgkazg](https://cloud.githubusercontent.com/assets/4446046/16629463/0972daa4-43b6-11e6-9d85-f503a862f03e.png)

Also wrong, 476 jobs, about 120 mcore, 350 score (*), 
845 cores, 500 mcore + 350 score

**Comment by aperezca** [comment]
This is interesting: I see 4-core jobs running at 41 sites…

![adeed6f](https://cloud.githubusercontent.com/assets/4446046/16733368/937a19aa-4781-11e6-950e-a47297fea43a.png)

…some of which don't have multicore pilots: T2_AT_Vienna, T2_FI_HIP, T2_BE_UCL, T2_ES_IFCA, T2_KR_KNU, T2_CN_Beijing, T2_IT_Rome, T2_RU_IHEP, T2_PL_Swierk, T2_BR_SPRACE

So the question is, what are we counting as multicore? Need to run the code by hand and check what is going on.

**Comment by amaltaro** [comment]
Scanning the output of the last run for T2_BR_SPRACE:
/afs/cern.ch/user/c/cmst1/CondorMonitoring/CondorMonitoring.json
this is a useful output:

```
                                             "Server": "cmssrv217.fnal.gov", 
                                                      {
                                                               "NCores": [
                                                                        {
                                                                                 "Cores": 1, 
                                                                                 "Pending": 0.0, 
                                                                                 "Running": 20.0
                                                                        }, 
                                                                        {
                                                                                 "Cores": 4, 
                                                                                 "Pending": 0.0, 
                                                                                 "Running": 1.0
                                                                        }
                                                               ], 
                                                               "Pending": 0.0, 
                                                               "Running": 21.0, 
                                                               "Type": "Processing"
                                                      }, 
                                             "Server": "cmsgwms-submit1.fnal.gov", 
                                                      {
                                                               "NCores": [
                                                                        {
                                                                                 "Cores": 1, 
                                                                                 "Pending": 6.0, 
                                                                                 "Running": 25.0
                                                                        }, 
                                                                        {
                                                                                 "Cores": 4, 
                                                                                 "Pending": 0.0, 
                                                                                 "Running": 0.0
                                                                        }
                                                               ], 
                                                               "Pending": 6.0, 
                                                               "Running": 25.0, 
                                                               "Type": "Processing"
                                                      }, 
                                             "Server": "cmsgwms-submit2.fnal.gov", 
                                                      {
                                                               "NCores": [
                                                                        {
                                                                                 "Cores": 1, 
                                                                                 "Pending": 78.0, 
                                                                                 "Running": 30.0
                                                                        }, 
                                                                        {
                                                                                 "Cores": 4, 
                                                                                 "Pending": 1.0, 
                                                                                 "Running": 0.0
                                                                        }
                                                               ], 
                                                               "Pending": 79.0, 
                                                               "Running": 30.0, 
                                                               "Type": "Processing"
                                                      }, 
                                             "Server": "vocms0311.cern.ch", 
                                                      {
                                                               "NCores": [
                                                                        {
                                                                                 "Cores": 4, 
                                                                                 "Pending": 0.0, 
                                                                                 "Running": 0.0
                                                                        }
                                                               ], 
                                                               "Pending": 0.0, 
                                                               "Running": 0.0, 
                                                               "Type": "Processing"
                                                      }, 
                                             "Server": "vocms0304.cern.ch", 
                                                      {
                                                               "NCores": [
                                                                        {
                                                                                 "Cores": 1, 
                                                                                 "Pending": 0.0, 
                                                                                 "Running": 26.0
                                                                        }, 
                                                                        {
                                                                                 "Cores": 4, 
                                                                                 "Pending": 0.0, 
                                                                                 "Running": 0.0
                                                                        }
                                                               ], 
                                                               "Pending": 0.0, 
                                                               "Running": 26.0, 
                                                               "Type": "Processing"
                                                      }, 
```

in summary, there seems to be 1 4-cores job running from cmssrv217. Antonio, can you have a look at that schedd and try to identify this job?

PS..: These Cores 4 with 0 pending and 0 running should not even show up in this file...

**Comment by aperezca** [comment]
Hi Alan, I don't have read permissions on that directory. Is this where the info gets collected to be submitted to dashboard? I see this is part of some /afs/cern.ch/user/c/cmst1/ area, who works there? who is the owner of that?  should I be added? :)

**Comment by aperezca** [comment]
I'll try to have a look at the schedds and see if I can spot some peculiar jobs like that. 

By the way, since I have been playing a bit with condor queries to schedds, I actually built a lightweight monitor at 

http://submit-3.t2.ucsd.edu/CSstoragePath/aperez/HTML/JobInfo/jobstatus_T1_24h.html

This is basically plotting the output of 

```
collector="cmsgwms-collector-global.cern.ch"
condor_q -pool $collector -global -constraint '(JobStatus == 2)' -af MATCH_GLIDEIN_CMSSite WMAgent_RequestName CRAB_ReqName RequestCPUs |sort |uniq -c
```

I guess what this is doing is something similar right? At least for the running jobs
