### ISSUE TITLE
Pressure on the global pool top collector induced by queries from this tool

### ISSUE THREAD

**Issue by aperezca** [amaltaro/scripts#7]
Another important point to understand is how much pressure queries from this tool are putting on the global pool collector. We see a noticeable difference in the UDP load when comparing CERN and FNAL collectors, and I see this tool has the CERN collector hardcoded as source of data, so that could potentially explain part of the difference.

After the discussion with HTCondor developers, there are two sides to this:

-schedd queries should not go to the top collector but to the child collector holding schedd info (cmsgwms-collector-global.cern.ch => cmsgwms-collector-global.cern.ch:9620), see:
https://cms-logbook.cern.ch/elog/Analysis+Operations/1265
https://github.com/dmwm/CRABServer/issues/5404

-queries should not request the full schedd list of classads but rather those attributes which are really required, see related changes in CRAB code https://github.com/dmwm/CRABServer/pull/5399

**Comment by juztas** [comment]
It is a small change in this script. Wait for Alan to confirm first pull request.

**Comment by juztas** [comment]
Changed in same pull request, see here: https://github.com/amaltaro/scripts/pull/6/commits/76e78698a0dc6740a82c7ecc2e589004c9d95baa

**Comment by amaltaro** [comment]
Can we close this one now?

**Comment by aperezca** [comment]
Yes, closing.
